#!/bin/sh
set -e

# Navigate to the Vim runtime directory
cd ~/.vimrc_runtime

# Create or overwrite the ~/.vimrc file
cat << 'EOF' > ~/.vimrc
" DO NOT EDIT THIS FILE
" Add your own customizations in ~/.vimrc_runtime/my_configs.vim

set runtimepath+=~/.vimrc_runtime

let data_dir = expand('~/.vimrc_runtime')

source ~/.vimrc_runtime/vimrcs/default_config.vim

if !empty(glob(data_dir . '/plugged/*'))
  source ~/.vimrc_runtime/vimrcs/plugin.vim
  source ~/.vimrc_runtime/vimrcs/basic.vim
  source ~/.vimrc_runtime/vimrcs/extended.vim
  source ~/.vimrc_runtime/vimrcs/plugin_config.vim
endif
EOF

# Print a success message
echo "Installed the Ultimate Vim configuration successfully! Enjoy :-), You need remove quit and then running again"
